@baseUrl = https://8080-igorgalvao1-correcaotar-pj6nj554am5.ws-us115.gitpod.io
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgVGFyZWZhcyIsInN1YiI6InVzdWFyaW8iLCJleHAiOjE3MjU0MDE5MTV9.zqDVcv7fap0G4yr0jJIJwnbDMcKGQJ42AjJhbCqT9ZI
###
GET {{baseUrl}}/tarefas

###
POST {{baseUrl}}/tarefas
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao": "Criar Formulário",
    "concluido": false
}

###
GET {{baseUrl}}/tarefas/4

###
PUT {{baseUrl}}/tarefas/1
Content-Type: application/json

{
    "descricao": "Testando Alteração",
    "concluido": false
}

###
DELETE {{baseUrl}}/tarefas/1